name: Main CI

concurrency:
  group: ci-${{ github.ref }}-main
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./tools/github-actions/setup
        with:
          enable-build-cache: 'true'
      - uses: ./.github/actions/setup-java
        with:
          install-jdk: 'true'
      - run: yarn build:swagger-gen
      - run: yarn build
      - uses: ./tools/github-actions/upload-build-output
  version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      nextVersionTag: ${{ steps.newVersion.outputs.nextVersionTag }}
      isPreRelease: ${{ contains( steps.newVersion.outputs.nextVersionTag, '-' ) || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./tools/github-actions/setup
      - name: New Version
        id: newVersion
        uses: ./tools/github-actions/new-version
        with:
          defaultBranch: main
          defaultBranchPrereleaseName: alpha
      - name: Create release
        if: github.event_name != 'pull_request'
        run: gh release create v${{ steps.newVersion.outputs.nextVersionTag }} --generate-notes ${{ contains( steps.newVersion.outputs.nextVersionTag, '-' ) && '--prerelease' || '' }} --target ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  checks:
    uses: ./.github/workflows/code-check.yml
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      affected: ${{ github.event_name == 'pull_request' }}
  test-publish:
    uses: ./.github/workflows/test-publish.yml
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    needs: [build]
  publish-packages:
    uses: ./.github/workflows/publish.yml
    permissions:
      packages: write
      contents: read
    secrets: inherit
    needs: [version, build, checks, test-publish]
    with:
      version: ${{ needs.version.outputs.nextVersionTag }}
      prerelease: ${{ needs.version.outputs.isPreRelease == 'true' }}
  cascading:
    runs-on: ubuntu-latest
    needs: [version, build, checks]
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./tools/github-actions/cascading
  documentation:
    runs-on: ubuntu-latest
    needs: [version, build, checks]
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'main'}}
    environment:
      name: azure-static-webapp
      url: ${{ steps.deploy.outputs.static_web_app_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate doc
        run: yarn doc:generate
      - name: Generate package json
        working-directory: ./generated-doc
        run: |
          yarn init -y
          yarn doc:update-package ./package.json --name @o3r/framework-doc --version ${{ needs.version.outputs.nextVersionTag }}
      - uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ./generated-doc
  deploy-documentation-azure-static-webapp:
    runs-on: ubuntu-latest
    needs: [documentation]
    environment:
      name: azure-static-webapp
      url: ${{ steps.deploy.outputs.static_web_app_url }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: documentation
          path: './generated-doc'
      - name: deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: ./generated-doc
          skip_app_build: true
          skip_api_build: true
          config_file_location: '.'
  deploy-documentation-github-pages:
    runs-on: ubuntu-latest
    needs: [documentation]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: documentation

