name: Main CI

concurrency:
  group: ci-${{ github.ref }}-main
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./tools/github-actions/setup
      - name: Generate doc
        run: yarn doc:generate
      - name: Generate package json
        working-directory: ./generated-doc
        run: yarn init -y
      - name: Update package json
        run: yarn doc:update-package ./generated-doc/package.json --name @o3r/framework-doc --version 1.0.0
      - uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ./generated-doc
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./generated-doc
  deploy-documentation-azure-static-webapp:
    runs-on: ubuntu-latest
    needs: [documentation]
    environment:
      name: azure-static-webapp
      url: ${{ steps.deploy.outputs.static_web_app_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: documentation
          path: './generated-doc'
      - name: deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: ./generated-doc
          skip_app_build: true
          skip_api_build: true
          config_file_location: '.'
  deploy-documentation-github-pages:
    runs-on: ubuntu-latest
    needs: [documentation]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

