name: Main CI

concurrency:
  group: ci-${{ github.ref }}-main
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  documentation:
    secrets: inherit
    needs: [version, build, checks]
    if: ${{ github.ref_name == 'main' || github.base_ref == 'main' }}
    uses: ./.github/workflows/documentation.yml
    with:
      version: ${{ needs.version.outputs.nextVersionTag }}
