name: Test publish

on:
  workflow_call:
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        required: false
        description: Token to use Nx Cloud token

jobs:
  test-publish:
    runs-on: ubuntu-20.04
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/download-build-output
      - uses: ./.github/actions/setup
        with:
          enable-build-cache: 'true'
          enable-e2e-cache: 'true'
      - uses: ./.github/actions/setup-java
        with:
          install-jdk: 'true'
      - name: Test
        run: yarn test-int
      - name: Prepare for publish generated app
        if: failure()
        run: zip -r test-app.zip ../test-app -x "../test-app/node_modules/*"
      - name: Publish generated app
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-app
          path: test-app.zip
